#!/bin/bash

# dev-note: do not add dependencies

set -e

PROGNAME="$0"

usage() {
    local err="$1"

    if [ ! -z "$err" ]; then
        echo "Error: $err" >&2
    fi

    echo "Usage: $PROGNAME [Options]" >&2
    echo "Options:" >&2
    echo "  -c      Output mode: C source code" >&2
    echo "  -v      Verbose mode" >&2

    exit 1
}

error() { echo "Error: $1" >&2; }
crit() { echo "Error: $1" >&2; exit 1; }

trim() {
    [[ "$1" =~ [[:space:]]*(.*[^[:space:]])[[:space:]]* ]]
    printf '%s' "${BASH_REMATCH[1]}"
}

OUTPUT_MODE=""
VERBOSE=false

while getopts "cv" opt; do
    case $opt in
    c) OUTPUT_MODE=C ;;
    v) VERBOSE=true ;;
    :) usage "Option -$OPTARG requires an argument" ;;
    \?) usage "Invalid option: -$OPTARG" ;;
    esac
done
shift $((OPTIND-1))

[ -z "$OUTPUT_MODE" ] && usage "Ouput mode is not selected"
[ ! -f "$1" ] && usage "Input file not provided or does not exist"

TMPL_FILE="$1"
OUTPUT_FILE=${2:-/dev/stdout}

temp=$(mktemp) || exit 1
trap 'rm -f "$temp"' EXIT

cat << EOF > "$temp"
/*
 * Generated by $PROGNAME
 */

#include "libdsc_db.h"

EOF

case "$OUTPUT_MODE" in
C)
    printf "const char *schema_setup_script = " >> "$temp"
    printf "\n\t\"PRAGMA foreign_keys = ON;\"" >> "$temp"
    lns=$'\t"'
    lne=$'"'
;;
esac

function gen_c_struct() {
    printf "const DBTable schema[] = {\n"

    while IFS= read -r line; do
        line=${line%%#*}

        IFS='|' read -ra raw_fields <<< "$line"

        fields=()
        for field in "${raw_fields[@]}"; do
            trimmed="${field#"${field%%[![:space:]]*}"}"
            trimmed="${trimmed%"${trimmed##*[![:space:]]}"}"
            fields+=("$trimmed")
        done

        case "${fields[0]}" in
        END)
            case $PARSE_STATE in
            COLUMN)
                printf "}\n"
                printf "\t\t}\n\t}"
            ;;
            *) ;;
            esac
        ;;
        TABLE)
            [ ! -n "${fields[1]}" ] && crit "TABLE tag requires table name"

            if [ "$PARSE_STATE" = "END" ]; then
                printf ",\n"
            fi

            printf "\t{\"${fields[1]}\", "
        ;;
        COLUMN)
            [ ! -n "${fields[1]}" ] && crit "COLUMN tag requires column name"
            [ ! -n "${fields[2]}" ] && crit "COLUMN tag requires column type"

            if [ "$PARSE_STATE" = "COLUMN" ]; then
                printf "},\n"
            else
                printf "\n\t\t(const DBColumn[]) {\n"
            fi

            printf "\t\t\t{\"${fields[1]}\", "

            case "${fields[2]}" in
            identity|id)    echo -n "DB_COLUMN_IDENTITY" ;;
            int)            echo -n "DB_COLUMN_INT" ;;
            text)           echo -n "DB_COLUMN_TEXT" ;;
            float)          echo -n "DB_COLUMN_FLOAT" ;;
            bin)            echo -n "DB_COLUMN_BINARY" ;;
            timestamp)      echo -n "DB_COLUMN_TIMESTAMP" ;;
            date)           echo -n "DB_COLUMN_DATE" ;;
            *) crit "Unrecognised column type: ${fields[2]}" ;;
            esac
        ;;
        *)
            if [ -n "${fields[0]}" ]; then
                error "Unrecognised tag: ${fields[0]}"
            fi
        esac

        if [ -n "${fields[0]}" ]; then
            PARSE_STATE="${fields[0]}"
        fi
    done

    printf "};\n"
}

function gen_sql_script() {
    PARSE_STATE=""

    TABLE_PRIMARY_INDEX=""

    while IFS= read -r line; do
        line=${line%%#*}

        IFS='|' read -ra raw_fields <<< "$line"

        fields=()
        for field in "${raw_fields[@]}"; do
            trimmed="${field#"${field%%[![:space:]]*}"}"
            trimmed="${trimmed%"${trimmed##*[![:space:]]}"}"
            fields+=("$trimmed")
        done

        case "${fields[0]}" in
        END)
            case $PARSE_STATE in
            COLUMN)
                if [ ! -z "$TABLE_PRIMARY_INDEX" ]; then
                    printf ",${lne}\n${lns}\tPRIMARY KEY ($TABLE_PRIMARY_INDEX)${lne}\n"
                    printf "${lns});${lne}"
                else
                    printf "${lne}\n${lns});${lne}\n";
                fi
            ;;
            *) ;;
            esac

            PARSE_STATE=""
            TABLE_PRIMARY_INDEX=""
        ;;
        TABLE)
            [ ! -n "${fields[1]}" ] && crit "TABLE tag requires table name"

            if [ "$PARSE_STATE" != "" ]; then
                crit "Missing END"
            fi

            printf "\n${lns}CREATE TABLE ${fields[1]} (${lne}\n"

            if [ -n "${fields[2]}" ]; then
                TABLE_PRIMARY_INDEX="${fields[2]}";
            fi
        ;;
        COLUMN)
            # COLUMN | <name> | <type> | <default>? | <foreign table>? | <foreign column>? | <foreign flags>
            [ ! -n "${fields[1]}" ] && crit "COLUMN tag requires column name"
            [ ! -n "${fields[2]}" ] && crit "COLUMN tag requires column type"

            [ "$PARSE_STATE" = "COLUMN" ] && printf ",${lne}\n"
            PARSE_STATE="COLUMN"

            echo -ne "${lns}\t${fields[1]}"

            case "${fields[2]}" in
            identity|id)   echo -n " INTEGER /* ID */" ;;
            int)        echo -n " INTEGER" ;;
            text)       echo -n " TEXT" ;;
            float)      echo -n " REAL" ;;
            bin)        echo -n " BLOB" ;;
            timestamp)  echo -n " REAL /* timestamp */" ;;
            date)       echo -n " TEXT /* DATE */" ;;
            *) crit "Unrecognised column type: ${fields[2]}" ;;
            esac

            # Default value
            if [ -n "${fields[3]}" ]; then
                echo -n " DEFAULT"

                case "${fields[2]}" in
                timestamp)
                    case "${fields[3]}" in
                    current) echo -n " (strftime('%s.%f', 'now'))" ;;
                    *) crit "Unrecognised default value for timestamp column type" ;;
                    esac
                ;;
                *) echo -n " ${fields[3]}" ;;
                esac
            fi

            # Foreign keys
            if [ -n "${fields[4]}" ]; then
                echo -n " REFERENCES ${fields[4]}"
                if [ -n "${fields[5]}" ]; then
                    echo -n "(${fields[5]})"
                fi

                case "${fields[6]}" in
                CASCADE) echo -n " ON DELETE CASCADE" ;;
                *) ;;
                esac
            fi
        ;;
        *)
            if [ -n "${fields[0]}" ]; then
                error "Unrecognised tag: ${fields[0]}"
            fi
        esac
    done
}

gen_sql_script << EOF >> "$temp"
TABLE   |schema_migrations
COLUMN  |version    | int
COLUMN  |applied   | timestamp | current
END

EOF

gen_sql_script < "$TMPL_FILE" >> "$temp"

case "$OUTPUT_MODE" in
C)
    printf ";\n\n" >> "$temp"

    gen_c_struct < "$TMPL_FILE" >> "$temp"
;;
esac

if [ "$VERBOSE" = "true" ]; then
    echo "===== Result ====" >&2
    cat "$temp" >&2
fi


mv "$temp" "$OUTPUT_FILE"

