/*
 * Generated by ../../scripts/gen_db.sh
 */

#include "libdsc_db.h"

const char *schema_setup_script = 
	"PRAGMA foreign_keys = ON;"
	"CREATE TABLE schema_migrations ("
	"	version INTEGER,"
	"	applied REAL /* timestamp */ DEFAULT (strftime('%s.%f', 'now'))"
	");"

	"CREATE TABLE artists ("
	"	id INTEGER /* ID */,"
	"	name TEXT,"
	"	PRIMARY KEY (id)"
	");"
	"CREATE TABLE albums ("
	"	id INTEGER /* ID */,"
	"	name TEXT,"
	"	artist_id INTEGER /* ID */ REFERENCES artists(id),"
	"	release_date TEXT /* DATE */,"
	"	PRIMARY KEY (id)"
	");"
	"CREATE TABLE tracks ("
	"	id INTEGER /* ID */,"
	"	title TEXT,"
	"	album_id INTEGER,"
	"	duration INTEGER,"
	"	track_no INTEGER,"
	"	file_path TEXT,"
	"	PRIMARY KEY (id)"
	");";

const DBTable schema[] = {
	{"artists", 
		(const DBColumn[]) {
			{"id", DB_COLUMN_IDENTITY},
			{"name", DB_COLUMN_TEXT}
		}
	},
	{"albums", 
		(const DBColumn[]) {
			{"id", DB_COLUMN_IDENTITY},
			{"name", DB_COLUMN_TEXT},
			{"artist_id", DB_COLUMN_IDENTITY},
			{"release_date", DB_COLUMN_DATE}
		}
	},
	{"tracks", 
		(const DBColumn[]) {
			{"id", DB_COLUMN_IDENTITY},
			{"title", DB_COLUMN_TEXT},
			{"album_id", DB_COLUMN_INT},
			{"duration", DB_COLUMN_INT},
			{"track_no", DB_COLUMN_INT},
			{"file_path", DB_COLUMN_TEXT}
		}
	}};
